# Generated by Django 5.0.1 on 2024-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekanikdata',
            name='odaNumarasi',
            field=models.CharField(choices=[('2001', '2001'), ('2002', '2002')], max_length=200),
        ),
    ]
