# Generated by Django 5.0.1 on 2024-04-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0002_alter_mekanikdata_odanumarasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekanikdata',
            name='odaNumarasi',
            field=models.CharField(max_length=200),
        ),
    ]
