# Generated by Django 5.0.1 on 2024-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0003_alter_mekanikdata_odanumarasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekanikdata',
            name='blokNumarasi',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='mekanikdata',
            name='katNumarasi',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
