# Generated by Django 5.0.1 on 2024-06-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0007_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='RCUDeneme',
        ),
    ]
