# Generated by Django 5.0.1 on 2024-06-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0012_rcudata_isdndactive_rcudata_islndactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blokKatOda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blokNumarasi', models.CharField(blank=True, max_length=200)),
                ('katNumarasi', models.CharField(blank=True, max_length=200)),
                ('odaNumarasi', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='rcudata',
            name='isLndDelayed',
        ),
        migrations.RemoveField(
            model_name='rcudata',
            name='isMurDelayed',
        ),
        migrations.AddField(
            model_name='mekanikdata',
            name='fidelio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcudata',
            name='isRoomVacant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcudata',
            name='lndEndTime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcudata',
            name='lndStartTime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcudata',
            name='murEndTime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcudata',
            name='murStartTime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='blokNumarasi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='comError',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='confortTemperature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='fanMode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='katNumarasi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='keylockFunction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='lowerSetpoint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='mode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='occupancyInput',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='odaNumarasi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='onOf',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='runningstatus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='setPoint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mekanikdata',
            name='upperSetpoint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rcudata',
            name='isAnyLightingActive',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
