# Generated by Django 5.0.1 on 2024-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0013_blokkatoda_remove_rcudata_islnddelayed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blokkatoda',
            name='isHVACConnected',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blokkatoda',
            name='isRCUConnected',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
