# Generated by Django 5.0.1 on 2024-07-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0015_rename_blokkatoda_blokkatodadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcudata',
            old_name='isRoomVacant',
            new_name='whoIsInRoom',
        ),
    ]
