# Generated by Django 5.0.1 on 2024-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0016_rename_isroomvacant_rcudata_whoisinroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('seaTemperature', models.FloatField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
