# Generated by Django 5.0.1 on 2024-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0017_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcudata',
            name='deviceType',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
