# Generated by Django 5.0.1 on 2024-07-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0018_rcudata_devicetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RCUData',
            new_name='RCUHelvarRouterData',
        ),
    ]
