# Generated by Django 5.0.1 on 2024-07-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0021_roomservicesdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='lndCustumerRequestTime',
            new_name='isLndActive',
        ),
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='lndStatus',
            new_name='isMurActive',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='murCustumerRequestTime',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='murStatus',
        ),
        migrations.AlterField(
            model_name='roomservicesdata',
            name='customerRequestTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomservicesdata',
            name='serviceEndTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomservicesdata',
            name='serviceResponceTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomservicesdata',
            name='serviceStartTime',
            field=models.DateTimeField(),
        ),
    ]
