# Generated by Django 5.0.1 on 2024-07-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0025_roomservicemurdata_customermurrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservicemurdata',
            name='serviceResponceTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
