# Generated by Django 5.0.1 on 2024-07-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0026_alter_roomservicemurdata_serviceresponcetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservicemurdata',
            name='serviceResponceTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
