# Generated by Django 5.0.1 on 2024-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0028_alter_roomservicemurdata_serviceresponcetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservicemurdata',
            name='serviceResponceTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
