# Generated by Django 5.0.1 on 2024-07-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0029_alter_roomservicemurdata_serviceresponcetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomServicesData',
        ),
        migrations.AddField(
            model_name='roomservicemurdata',
            name='requestResponceTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
