# Generated by Django 5.0.1 on 2024-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0030_delete_roomservicesdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservicemurdata',
            name='ackStatus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roomservicemurdata',
            name='ackTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
