# Generated by Django 5.0.1 on 2024-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0031_roomservicemurdata_ackstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomServiceLNDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blokNumarasi', models.CharField(blank=True, max_length=200)),
                ('katNumarasi', models.CharField(blank=True, max_length=200)),
                ('odaNumarasi', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('customerRequest', models.CharField(blank=True, max_length=200)),
                ('customerRequestTime', models.DateTimeField(blank=True, null=True)),
                ('serviceStartTime', models.DateTimeField(blank=True, null=True)),
                ('serviceEndTime', models.DateTimeField(blank=True, null=True)),
                ('serviceResponceTime', models.CharField(blank=True, max_length=200, null=True)),
                ('requestResponceTime', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.CharField(blank=True, max_length=200)),
                ('ackStatus', models.CharField(blank=True, max_length=200)),
                ('ackTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='roomservicemurdata',
            old_name='customerMurRequest',
            new_name='customerRequest',
        ),
    ]
