# Generated by Django 5.0.1 on 2024-07-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0032_roomservicelnddata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='upperGecikmeLimiti',
            new_name='dashboardServiceReqResponceTimeUpperLimit',
        ),
    ]
