# Generated by Django 5.0.1 on 2024-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0034_appsettings_lnddelaythreshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservicemurdata',
            name='isDelayed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
