# Generated by Django 5.0.1 on 2024-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0035_roomservicemurdata_isdelayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservicemurdata',
            name='delayDuration',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
