# Generated by Django 5.0.1 on 2024-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0036_roomservicemurdata_delayduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservicemurdata',
            name='delayDuration',
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='lndDelayThreshold',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='murDelayThreshold',
            field=models.IntegerField(default=60),
        ),
    ]
