# Generated by Django 5.0.1 on 2024-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0037_remove_roomservicemurdata_delayduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='cleanedRoomDisplayTime',
            field=models.IntegerField(default=60),
        ),
    ]
