# Generated by Django 5.0.1 on 2024-07-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0038_appsettings_cleanedroomdisplaytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='cleanedRoomDisplayTime',
            new_name='cleanedRoomDisplayTimeThreshold',
        ),
    ]
