# Generated by Django 5.0.1 on 2024-07-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0039_rename_cleanedroomdisplaytime_appsettings_cleanedroomdisplaytimethreshold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomServiceLNDData',
        ),
    ]
