# Generated by Django 5.0.1 on 2024-07-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0040_delete_roomservicelnddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='isAnyLightingActive',
            new_name='anyLightingActive',
        ),
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='isDndActive',
            new_name='dndActive',
        ),
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='isLndActive',
            new_name='lndActive',
        ),
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='isMurActive',
            new_name='murActive',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='lndEndTime',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='lndStartTime',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='murEndTime',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='murStartTime',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='whoIsInRoom',
        ),
        migrations.AddField(
            model_name='blokkatodadata',
            name='ip',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blokkatodadata',
            name='isHelvarConnected',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blokkatodadata',
            name='kullanilanMarka',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blokkatodadata',
            name='odaTipi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcuhelvarrouterdata',
            name='doorOpen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rcuhelvarrouterdata',
            name='roomOccupied',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
