# Generated by Django 5.0.1 on 2024-07-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0041_rename_isanylightingactive_rcuhelvarrouterdata_anylightingactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcuhelvarrouterdata',
            name='hkInRoom',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
