# Generated by Django 5.0.1 on 2024-07-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0043_alter_roomservicemurdata_customerrequesttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservicemurdata',
            name='customerRequestTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
