# Generated by Django 5.0.1 on 2024-07-14 16:40

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0045_alter_roomservicemurdata_customerrequesttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blokNumarasi', models.CharField(blank=True, max_length=200)),
                ('katNumarasi', models.CharField(blank=True, max_length=200)),
                ('odaNumarasi', models.CharField(blank=True, max_length=200)),
                ('alarmType', models.CharField(blank=True, max_length=200)),
                ('alarmStatus', models.CharField(blank=True, max_length=200)),
                ('rcuAlarmDetails', jsonfield.fields.JSONField(blank=True, default=list)),
                ('hvacAlarmDetails', jsonfield.fields.JSONField(blank=True, default=list)),
                ('lightingAlarmDetails', jsonfield.fields.JSONField(blank=True, default=list)),
                ('openDoorAlarmDetails', jsonfield.fields.JSONField(blank=True, default=list)),
                ('helvarAlarmDetails', jsonfield.fields.JSONField(blank=True, default=list)),
                ('alarmStartTime', models.DateTimeField(blank=True, null=True)),
                ('alarmEndTime', models.DateTimeField(blank=True, null=True)),
                ('ackStatus', models.CharField(blank=True, max_length=200)),
                ('ackTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
