# Generated by Django 5.0.1 on 2024-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0046_alarmsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='fixedAlarmDisplayTimeThreshold',
            field=models.IntegerField(default=45),
        ),
    ]
