# Generated by Django 5.0.1 on 2024-07-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0047_appsettings_fixedalarmdisplaytimethreshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmsdata',
            old_name='openDoorAlarmDetails',
            new_name='doorSystAlarmDetails',
        ),
    ]
