# Generated by Django 5.0.1 on 2024-07-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0049_delete_weatherdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='daliInputDevices',
            new_name='outputDevices',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='daliOutputDevices',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='onboardInputDevices',
        ),
        migrations.RemoveField(
            model_name='rcuhelvarrouterdata',
            name='onboardOutputDevices',
        ),
    ]
