# Generated by Django 5.0.1 on 2024-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0050_rename_daliinputdevices_rcuhelvarrouterdata_outputdevices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='dashboardServiceReqResponceTimeUpperLimit',
            field=models.IntegerField(default=60),
        ),
    ]
