# Generated by Django 5.0.1 on 2024-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0051_alter_appsettings_dashboardservicereqresponcetimeupperlimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='dashboardServiceReqResponceTimeUpperLimit',
            new_name='dashboardServiceResponceTimeUpperLimit',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='dashboardReqResponceTimeUpperLimit',
            field=models.IntegerField(default=30),
        ),
    ]
