# Generated by Django 5.0.1 on 2024-07-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0052_rename_dashboardservicereqresponcetimeupperlimit_appsettings_dashboardserviceresponcetimeupperlimit_'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekanikdata',
            name='pmsComError',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
