# Generated by Django 5.0.1 on 2024-08-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0054_alarmsdata_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mekanikdata',
            name='pmsComError',
        ),
    ]
