# Generated by Django 5.0.1 on 2024-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0063_account_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='account',
            name='dashboard',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], default='ACCESS', max_length=15),
        ),
    ]
