# Generated by Django 5.0.1 on 2024-12-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0064_remove_account_phonenumber_account_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alarms',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], default='ACCESS', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='reports',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], default='ACCESS', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='roomServices',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], default='ACCESS', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='roomStatus',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], default='ACCESS', max_length=15),
        ),
    ]
