# Generated by Django 5.0.1 on 2024-12-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0065_account_alarms_account_reports_account_roomservices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alarms',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='reports',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], max_length=15),
        ),
    ]
