# Generated by Django 5.0.1 on 2024-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0066_alter_account_alarms_alter_account_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dashboard',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='roomServices',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='roomStatus',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], max_length=15),
        ),
    ]
