# Generated by Django 5.0.1 on 2024-12-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0067_alter_account_dashboard_alter_account_roomservices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dashboard',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], default='ACCESS', max_length=15),
        ),
    ]
