# Generated by Django 5.0.1 on 2024-12-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0068_alter_account_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='alarms',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roomServices',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roomStatus',
        ),
    ]
