# Generated by Django 5.0.1 on 2024-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0069_remove_account_alarms_remove_account_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dashboard',
            field=models.CharField(choices=[('ACCESS', 'ACCESS'), ('NONACCESS', 'NONACCESS')], max_length=15),
        ),
    ]
