# Generated by Django 5.0.1 on 2024-12-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0071_account_alarms_account_reports_account_roomservices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blokkatodadata',
            name='odaTipi',
        ),
    ]
