# Generated by Django 5.0.1 on 2024-12-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0072_remove_blokkatodadata_odatipi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blokkatodadata',
            old_name='kullanilanMarka',
            new_name='isHKServiceConnected',
        ),
    ]
