# Generated by Django 5.0.1 on 2024-12-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0074_blokkatoda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlokKatOda',
        ),
    ]
