# Generated by Django 5.0.1 on 2024-12-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0075_delete_blokkatoda'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlokKatOda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blokNumarasi', models.CharField(max_length=200, unique=True, verbose_name='Blok Numarası')),
                ('isGenelMahal', models.CharField(default='0', max_length=1, verbose_name='Genel Mahal mi?')),
            ],
            options={
                'verbose_name': 'Blok Kat Oda',
                'verbose_name_plural': 'Blok Kat Odalar',
                'ordering': ['blokNumarasi'],
            },
        ),
    ]
