# Generated by Django 5.0.1 on 2024-12-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0077_alter_blokkatodadata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blokkatoda',
            name='blokNumarasi',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blokkatoda',
            name='isGenelMahal',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='blokKatOda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odaVerileri', to='tridiumBackendApp.blokkatoda'),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='isHKServiceConnected',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='isHVACConnected',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='isHelvarConnected',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='isRCUConnected',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='katNumarasi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='odaNumarasi',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
