# Generated by Django 5.0.1 on 2024-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0078_alter_blokkatoda_bloknumarasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blokkatodadata',
            name='port',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
