# Generated by Django 5.0.1 on 2024-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0079_blokkatodadata_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blokkatodadata',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blokkatodadata',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
