# Generated by Django 5.0.1 on 2024-12-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridiumBackendApp', '0080_alter_blokkatodadata_ip_alter_blokkatodadata_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcuhelvarrouterdata',
            old_name='doorOpen',
            new_name='doorOpenAlarm',
        ),
    ]
